### Отчет по лаборторной работе №5 "Линейные модели, SVM и деревья решений"

In [237]:
import numpy as np
import pandas as pd
import seaborn as sns
import warnings
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.svm import LinearSVC
from sklearn.preprocessing import Normalizer
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, f1_score
from sklearn.neighbors import KNeighborsRegressor, KNeighborsClassifier
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV, KFold, ShuffleSplit
%matplotlib inline 
sns.set(style="ticks")
%matplotlib inline 
sns.set(style='ticks')

### подготовка датасета
#### Medical Cost (personal datasets)

In [175]:
data = pd.read_csv('reg.csv')

In [176]:
data.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [177]:
data.shape

(1338, 7)

In [178]:
data.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [179]:
data.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [180]:
cat_coll = []
for col in data.columns:
    if data[col].dtype == 'object':
        cat_coll.append(col)
en_cat = {}
for col in cat_coll:
    le = LabelEncoder()
    data[[col]] = le.fit_transform(data[col])  
    en_cat[col] = le
data.dtypes

age           int64
sex           int64
bmi         float64
children      int64
smoker        int64
region        int64
charges     float64
dtype: object

In [181]:
# разделение выборки на обучающую и тестовую
x = data.iloc[:, 0:5]
y = data.iloc[:, 6]

In [182]:
x.dtypes

age           int64
sex           int64
bmi         float64
children      int64
smoker        int64
dtype: object

In [183]:
y.dtypes

dtype('float64')

In [184]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.3, random_state=42)
len(xtrain), len(xtest), len(ytrain), len(ytest)

(936, 402, 936, 402)

### обучение моделей

### линейная регрессия

In [185]:
lr = LinearRegression()
lr.fit(xtrain, ytrain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [186]:
lr.intercept_, lr.coef_

(-12538.439849853163,
 array([  261.91061673,   136.65119758,   333.36099462,   432.1792927 ,
        23618.76182167]))

In [187]:
y_predtest = lr.predict(xtest)
y_predtest

array([ 8504.25952786,  6897.83941087, 36805.01178274,  9525.01640181,
       26834.15783554, 11236.53827843,   -56.51533813, 16996.53931939,
         558.86901551, 11292.49638115, 28504.83781808,  9398.41804442,
        5353.29915879, 38679.23753917, 40572.74207294, 37372.20787154,
       15387.38620563, 36033.31348368,  9292.40371143, 31304.88883148,
        4274.20100087, 10592.29487706,  2708.68730205,  6493.02810907,
       11227.74003336, 12498.97075764, 14877.16806499,  5963.85891638,
        9503.12017865,  2360.10282672,  9434.17913244, 12999.67895742,
        4585.98098388,  3265.96837276,  4840.89651399, 12653.62349137,
        2194.59265213,  9123.3897013 , 33175.85413453, 32812.24167496,
        4132.88277765,  4243.29138982, 14495.05758702, 11538.30865769,
        9023.27584285, 12650.54437942,  5036.97193595,  3406.53561573,
       35766.6625433 ,  9379.5276352 , 16062.93310871,  2535.59415356,
       12177.97650916,  1021.65843332, 13742.82492927, 12262.32230678,
      

In [188]:
y_predtrain = lr.predict(xtrain)
y_predtrain

array([ 1.38256364e+04,  8.84686317e+03,  1.35354871e+04,  3.58512392e+04,
        3.38103569e+04,  3.55911066e+04,  6.13903101e+03,  5.67096539e+03,
        1.67676441e+04,  7.95099695e+03,  3.77437564e+04,  5.22458952e+03,
        8.16931607e+03,  1.05685742e+04,  3.04312340e+04,  5.03648650e+03,
        3.33007217e+03,  1.61765824e+04,  3.33935980e+03,  6.42236104e+03,
        9.87609203e+03, -5.24914346e+02,  2.98210581e+04,  8.10253272e+03,
        1.03688911e+04,  5.83263995e+03,  7.93654581e+03,  1.18355359e+04,
        2.93262858e+04,  9.78747712e+03,  1.10151810e+04,  5.93664857e+03,
        3.99691789e+03,  1.28137343e+03,  8.07719180e+03,  1.14957032e+04,
        1.05625879e+04,  9.04557861e+03,  5.88077324e+03,  4.47638952e+03,
        7.08441041e+03,  3.40634889e+04,  3.34643225e+04,  3.40543859e+03,
        4.02327139e+04,  2.88466581e+04,  1.12328980e+04,  4.37549228e+03,
        1.71477741e+04,  3.94212298e+03,  9.56114464e+03,  2.97400191e+04,
        1.66160492e+04,  

In [189]:
ytest.values

array([ 9095.06825 ,  5272.1758  , 29330.98315 ,  9301.89355 ,
       33750.2918  ,  4536.259   ,  2117.33885 , 14210.53595 ,
        3732.6251  , 10264.4421  , 18259.216   ,  7256.7231  ,
        3947.4131  , 46151.1245  , 48673.5588  , 44202.6536  ,
        9800.8882  , 42969.8527  ,  8233.0975  , 21774.32215 ,
        5080.096   ,  7441.501   ,  1256.299   ,  2755.02095 ,
       11085.5868  , 10923.9332  , 12644.589   , 18804.7524  ,
        9715.841   ,  1131.5066  , 15828.82173 , 11842.62375 ,
        2020.5523  ,  5693.4305  ,  2904.088   ,  7448.40395 ,
        2597.779   ,  7337.748   , 23887.6627  , 38709.176   ,
        4687.797   ,  2643.2685  , 11674.13    , 12124.9924  ,
        4889.9995  , 12333.828   ,  3579.8287  ,  4391.652   ,
       42124.5153  ,  4463.2051  , 13887.204   ,  1719.4363  ,
       28476.73499 ,  1708.92575 , 10594.2257  , 25333.33284 ,
        3645.0894  , 38746.3551  , 11848.141   , 10564.8845  ,
       13880.949   ,  4753.6368  , 27941.28758 ,  8017.

In [190]:
# средняя абсолютная ошибка
print('ma (train): {}'.format(mean_absolute_error(ytrain, y_predtrain)))
print('ma (test): {}'.format(mean_absolute_error(ytest, y_predtest)))

ma (train): 4253.809194427617
ma (test): 4171.01308409371


In [191]:
# средняя квадратичная ошибка
print('ms (train): {}'.format(mean_squared_error(ytrain, y_predtrain)))
print('ms (test): {}'.format(mean_squared_error(ytest, y_predtest)))

ms (train): 37878481.85624297
ms (test): 34003912.39316076


In [192]:
# среднее квадратичное отклонение
print('sq (train): {}'.format(r2_score(ytrain, y_predtrain)))
print('sq (test): {}'.format(r2_score(ytest, y_predtest)))

sq (train): 0.7413880155089706
sq (test): 0.7680881643600721


### svm

In [240]:
datac = pd.read_csv('clas.csv')[:1000]

In [241]:
datac.head()

Agency    Agency Type Distribution Channel                     Product Name  \
0    CBH  Travel Agency              Offline               Comprehensive Plan   
1    CBH  Travel Agency              Offline               Comprehensive Plan   
2    CWT  Travel Agency               Online  Rental Vehicle Excess Insurance   
3    CWT  Travel Agency               Online  Rental Vehicle Excess Insurance   
4    CWT  Travel Agency               Online  Rental Vehicle Excess Insurance   

  Claim  Duration Destination  Net Sales  Commision (in value) Gender  Age  
0    No       186    MALAYSIA      -29.0                  9.57      F   81  
1    No       186    MALAYSIA      -29.0                  9.57      F   71  
2    No        65   AUSTRALIA      -49.5                 29.70    NaN   32  
3    No        60   AUSTRALIA      -39.6                 23.76    NaN   32  
4    No        79       ITALY      -19.8                 11.88    NaN   41

In [242]:
datac.shape

(1000, 11)

In [243]:
datac.isnull().sum()

Agency                    0
Agency Type               0
Distribution Channel      0
Product Name              0
Claim                     0
Duration                  0
Destination               0
Net Sales                 0
Commision (in value)      0
Gender                  767
Age                       0
dtype: int64

In [244]:
datac.dtypes

Agency                   object
Agency Type              object
Distribution Channel     object
Product Name             object
Claim                    object
Duration                  int64
Destination              object
Net Sales               float64
Commision (in value)    float64
Gender                   object
Age                       int64
dtype: object

In [245]:
datac = datac.drop(columns='Gender')

In [246]:
cat_coll = []
for col in datac.columns:
    if datac[col].dtype == 'object':
        cat_coll.append(col)
en_cat = {}
for col in cat_coll:
    le = LabelEncoder()
    datac[[col]] = le.fit_transform(datac[col])  
    en_cat[col] = le
datac.dtypes

Agency                    int64
Agency Type               int64
Distribution Channel      int64
Product Name              int64
Claim                     int64
Duration                  int64
Destination               int64
Net Sales               float64
Commision (in value)    float64
Age                       int64
dtype: object

In [247]:
datac.isnull().sum()

Agency                  0
Agency Type             0
Distribution Channel    0
Product Name            0
Claim                   0
Duration                0
Destination             0
Net Sales               0
Commision (in value)    0
Age                     0
dtype: int64

In [248]:
xc, yc = datac[datac.columns[range(9)]], datac[datac.columns[[9]]]
print('x:\n', xc.columns)
print('y:\n', yc.columns)

x:
 Index(['Agency', 'Agency Type', 'Distribution Channel', 'Product Name',
       'Claim', 'Duration', 'Destination', 'Net Sales',
       'Commision (in value)'],
      dtype='object')
y:
 Index(['Age'], dtype='object')


In [249]:
normx = Normalizer().fit(xc)
xc_n = normx.transform(xc)
xc_n

array([[ 0.01049344,  0.00524672,  0.        , ...,  0.14166138,
        -0.15215482,  0.05021109],
       [ 0.01049344,  0.00524672,  0.        , ...,  0.14166138,
        -0.15215482,  0.05021109],
       [ 0.05696054,  0.01139211,  0.01139211, ...,  0.        ,
        -0.56390935,  0.33834561],
       ...,
       [ 0.07063224,  0.01177204,  0.01177204, ...,  0.28252897,
         0.43556549,  0.        ],
       [ 0.17459279,  0.0290988 ,  0.0290988 , ...,  0.64017356,
         0.61107476,  0.        ],
       [ 0.05049332,  0.00841555,  0.00841555, ...,  0.40394654,
         0.67324423,  0.        ]])

In [250]:
xtrainc, xtestc, ytrainc, ytestc = train_test_split(xc_n, yc, test_size=0.3, random_state=42)
len(xtrainc), len(xtestc), len(ytrainc), len(ytestc)

(700, 300, 700, 300)

In [251]:
lsvc = LinearSVC(C=1.0, max_iter=1000, verbose=10)
lsvc

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=10)

In [252]:
lsvc.fit(xtrainc, ytrainc.values.ravel())

[LibLinear]

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=10)

In [253]:
ypred_ctrain = lsvc.predict(xtrainc)
y_pred_ctest = lsvc.predict(xtestc)

print('train accuracy (%): {} %'.format(accuracy_score(ytrainc, ypred_ctrain) * 100))
print('test accuracy (%): {} %'.format(accuracy_score(ytestc, y_pred_ctest) * 100))

train accuracy (%): 47.714285714285715 %
test accuracy (%): 48.333333333333336 %


In [254]:
print('матрица ошибок: строки – истинное значение, столбцы – предсказанное значение')
print('train\n', confusion_matrix(ytrainc, ypred_ctrain))
print('test\n', confusion_matrix(ytestc, y_pred_ctest))

матрица ошибок: строки – истинное значение, столбцы – предсказанное значение
train
 [[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0 13]]
test
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 2]]


In [255]:
print('train:', precision_score(ytrainc, ypred_ctrain, average='weighted'))
print('test:', precision_score(ytestc, y_pred_ctest, average='weighted'))

train: 0.2759646923534461
test: 0.2881639900770335


In [256]:
print('train:', f1_score(ytrainc, ypred_ctrain, average='weighted'))
print('test:', f1_score(ytestc, y_pred_ctest, average='weighted'))

train: 0.3424345726881972
test: 0.3568002352372158


### дерево

In [286]:
tree = DecisionTreeClassifier(random_state=42)

In [287]:
tree.fit(xtrainc, ytrainc)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=42, splitter='best')

In [288]:
list(zip(xc.columns.values, tree.feature_importances_))

[('Agency', 0.08722336840906048),
 ('Agency Type', 0.07539056269469359),
 ('Distribution Channel', 0.08379155489597753),
 ('Product Name', 0.1080609600647266),
 ('Claim', 0.00212916098890403),
 ('Duration', 0.15053149373080293),
 ('Destination', 0.14379668828474473),
 ('Net Sales', 0.11815727830594033),
 ('Commision (in value)', 0.2309189326251498)]

In [289]:
yt_predtrain = tree.predict(xtrainc)
yt_predtest = tree.predict(xtestc)

In [290]:
print('train accuracy (%): {} %'.format(accuracy_score(ytrainc, yt_predtrain) * 100))
print('test accuracy (%): {} %'.format(accuracy_score(ytestc, yt_predtest) * 100))

train accuracy (%): 97.42857142857143 %
test accuracy (%): 36.0 %


In [291]:
print('матрица ошибок:')
print('train\n', confusion_matrix(ytrainc, yt_predtrain))
print('test\n', confusion_matrix(ytestc, yt_predtest))

матрица ошибок:
train
 [[ 3  0  0 ...  0  0  0]
 [ 0  3  0 ...  0  0  0]
 [ 0  0  3 ...  0  0  0]
 ...
 [ 0  0  0 ...  1  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0 18]]
test
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 3]]


In [292]:
print('train:', precision_score(ytrainc, yt_predtrain, average='weighted'))
print('test:', precision_score(ytestc, yt_predtest, average='weighted'))

train: 0.9741021561623425
test: 0.3756529581529582


In [293]:
print('train:', f1_score(ytrainc, yt_predtrain, average='weighted'))
print('test:', f1_score(ytestc, yt_predtest, average='weighted'))

train: 0.9730199683483137
test: 0.36515105795545705


### подбор одного гиперпараметра с использованием GridSearchCV и кросс-валидации

### svm

In [328]:
param = [{'C': np.array(np.arange(0.8, 3.1, 0.1)),
               'max_iter': np.array([1000, 5000, 10000, 25000, 50000])}]
lsvc_grid = GridSearchCV(LinearSVC(), param, cv=ShuffleSplit(n_splits=20, test_size=0.3), scoring='accuracy', 
                         n_jobs=-1, 
                        )
lsvc_grid.fit(xc_n, yc.values.ravel())
# считает ~2 мин

GridSearchCV(cv=ShuffleSplit(n_splits=20, random_state=None, test_size=0.3, train_size=None),
             error_score='raise-deprecating',
             estimator=LinearSVC(C=1.0, class_weight=None, dual=True,
                                 fit_intercept=True, intercept_scaling=1,
                                 loss='squared_hinge', max_iter=1000,
                                 multi_class='ovr', penalty='l2',
                                 random_state=None, tol=0.0001, verbose=0),
             iid='warn', n_jobs=-1,
             param_grid=[{'C': array([0.8, 0.9, 1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ,
       2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. ]),
                          'max_iter': array([ 1000,  5000, 10000, 25000, 50000])}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=0)

In [329]:
lsvc_grid.best_params_

{'C': 2.5, 'max_iter': 1000}

In [330]:
lsvc_grid.best_estimator_

LinearSVC(C=2.5, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [331]:
lsvc_grid.best_score_

0.4776666666666667

### дерево

In [332]:
param = [{'random_state': np.array([42]),
               'max_depth': np.array([None, 10, 50, 100]),
               'min_samples_split': np.array(range(2, 11)),
               'min_samples_leaf': np.array(range(1, 11))
              }]
tree_grid = GridSearchCV(DecisionTreeClassifier(), param, cv=ShuffleSplit(n_splits=20, test_size=0.3), scoring='accuracy', 
                         n_jobs=-1, 
                        )
tree_grid.fit(xc_n, yc.values.ravel())

GridSearchCV(cv=ShuffleSplit(n_splits=20, random_state=None, test_size=0.3, train_size=None),
             error_score='raise-deprecating',
             estimator=DecisionTreeClassifier(class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fractio....0,
                                              presort=False, random_state=None,
                                              splitter='best'),
             iid='warn', n_jobs=-1,
             param_grid=[{'max_depth': array([None, 10,

In [333]:
tree_grid.best_params_

{'max_depth': 10,
 'min_samples_leaf': 9,
 'min_samples_split': 2,
 'random_state': 42}

In [334]:
tree_grid.best_estimator_

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=10,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=9, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=42, splitter='best')

In [335]:
tree_grid.best_score_

0.4735

### обучим снова с найденными гиперпараметрами

In [336]:
lsvc_grid.best_estimator_.fit(xtrainc, ytrainc.values.ravel())

y_predctrainnew = lsvc_grid.best_estimator_.predict(xtrainc)
y_predctestnew = lsvc_grid.best_estimator_.predict(xtestc)

print('train accuracy (%): {} %'.format(accuracy_score(ytrainc, ypred_ctrain) * 100))
print('test accuracy (%): {} %'.format(accuracy_score(ytestc, y_pred_ctest) * 100))

print('new train accuracy (%): {} %'.format(accuracy_score(ytrainc, y_predctrainnew) * 100))
print('new test accuracy (%): {} %'.format(accuracy_score(ytestc, y_predctestnew) * 100))

train accuracy (%): 47.714285714285715 %
test accuracy (%): 48.333333333333336 %
new train accuracy (%): 48.0 %
new test accuracy (%): 48.333333333333336 %


In [337]:
tree_grid.best_estimator_.fit(xtrainc, ytrainc.values.ravel())

yt_predtrainnew = tree_grid.best_estimator_.predict(xtrainc)
yt_predtestnew = tree_grid.best_estimator_.predict(xtestc)

print('train accuracy (%): {} %'.format(accuracy_score(ytrainc, yt_predtrain) * 100))
print('test accuracy (%): {} %'.format(accuracy_score(ytestc, yt_predtest) * 100))

print('new train accuracy (%): {} %'.format(accuracy_score(ytrainc, yt_predtrainnew) * 100))
print('new test accuracy (%): {} %'.format(accuracy_score(ytestc, yt_predtestnew) * 100))

train accuracy (%): 97.42857142857143 %
test accuracy (%): 36.0 %
new train accuracy (%): 55.285714285714285 %
new test accuracy (%): 47.333333333333336 %


#### с новыми гиперпараметрами модель обучилась лучше